spring:
  datasource:
    url: jdbc:mysql://localhost:13306/DB_JPA?characterEncoding=utf8&useSSL=false
    username: root
    password: Lyp82nlf
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
